name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip and Prepare
        run: |
          unzip -o PoliceAssistant.zip -d temp_extract
          cp -r temp_extract/*. || true
          cp -r temp_extract/.*. || true
          rm -rf PoliceAssistant.zip temp_extract
          ls -la
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Debug APK
        run: |
          chmod +x gradlew
         ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PoliceAssistant-APK
          path: app/build/outputs/apk/debug/*.apk
